### ISSUE TITLE
I have a problem running Sequence Matrix on mac with big sur, it does not open at all.

### ISSUE THREAD

**Issue by RomiBRC** [gaurav/taxondna#100]

**Comment by RomiBRC** [comment]
I have a problem running Sequence Matrix on mac with big sur, it does not open at all.

**Comment by konskons11** [comment]
I had experienced the same problem with the version 1.9 downloaded on MacOS. Do you have dark theme mode enabled ? Switching to light theme mode should solve it as it worked for me.

**Comment by gaurav** [comment]
Are y'all still having these issues with the latest release? It should have (hopefully) fixed some macOS-related issues.
